### ISSUE TITLE
Bestilling af bøger

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/content-first#133]
Meta-issue omkring bestillinger.

- [x] testlogin der virker med DÅP
    - [x] testbruger (brugerid, pin, agency)
    - [x] client_id, client_secret
- [ ]  client
  - [x] Prototype af (virkende) bestil-knap med softcoded afhentningssted+token  (Pull request: #135, Done)
  - [x] endeligt valg af design for bestilling (@AndersFriisBrodsgaard #127, Done except status for bestillinger)
  - [x] Overlay med confirm + vælg branch. (@rasmuserik kigger på denne, #147)
  - [x] Vis kun bestil-knapper hvis vi har en indlogget bruger #148
  - [x] Hent branch+token fra server, og placer i state (+ server dummy-implementation)
  - [ ] ~~Side med oversigt / status for bestilte bøger (#123,~~ senere?)
  - [ ] ~~Synkroniser liste over bestillinger med server~~ (#150, senere?)
  - [x] ~~Eventuel opsaml bestillinger som adfærdsdata~~ (del af #76 / #154 , senere?)
  - [x] Bestille ~~alle~~ bøger i en lister (ikke huskeliste) (#122)
- [x] server - openplatform-token skal eksporteres i `/user` endpointet #149
- [ ] ~~server husk bestillinger~~ (#150, evt. relateret til #76, senere?)
- [ ] openplatform (@rasmuserik og @vibjerg skal nok koordinere her, - foreløbigt virker det nogenlunde som det er)
  - [x] sørg for at vi få agency med ud i `/user` endpointet, da vi har brug for dette (pull requests: dbcdk/serviceprovider#884, dbcdk/serviceprovider#885, Done.)
  - [ ] sikr at order melder fejl ved bestilling af materiale der ikke kan bestilles (dbcdk/serviceprovider#887, senere?)
  - [ ] afklar om bestilling gælder alle udgaver (evt. forskelligt ved forskellige versioner af DÅP). Ifølge koden ser det ud til at gælde alle, men ifølge videresendt mail fra bibliotekar er det "Kun den bestilte udgave kan bruges".
  - [ ] opdatér openplatform npm-modulet til seneste udgave af DÅP, og sikr at det ligger hos DBC (dbcdk/serviceprovider#886, senere?)
- [x] hejmdal: 
  - [x] return DÅP-token dbcdk/hejmdal#404 (@vibjerg er i gang)

**Comment by AndersFriisBrodsgaard** [comment]
![overlay-bestil](https://user-images.githubusercontent.com/18284484/34777449-a9336276-f61a-11e7-9898-81d935ec66c9.png)

**Comment by KiraH** [comment]
OK
