### ISSUE TITLE
Tilføjelse af kommentarer til sociale liste

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#203]
- Det skal være muligt at kommentere en liste.
- Nyeste kommentar (1 el. 2) præsenteres, men skal optræde kronologisk, hvis der klikkes på ”Vis alle” 
- Der skal skrives hvornår kommentaren er givet (1 time, 2 dage osv.).
- I denne version er der kun kommentarer til simple-lister (ikke visuelle).

**API**
Tilføjelse af kommentarer sker gennem det generiske object endpoint:
https://github.com/DBCDK/content-first/blob/201-list-api/doc/endpoints.md#post-object-or-put-objectid

**Skal i denne version ikke understøtte:**
- Billeder og video

**Todo**
- [x] setup redux til kommentarer
- [x] inputfelt til kommentarer
- [x] gem kommentarer i reducer
- [x] gem kommentarer via /object endpoint
- [x] hent kommentarer til liste
- [x] Vis seneste kommentar
- [x] Hvis der er mere end én kommentar, skal der være mulighed for at vise alle kommentarer

**Comment by KiraH** [comment]
testet OK
